print ("Michaela Alperes Siena")
print ("Laylay, Boac, Marinduque")
print ("February 4, 2002")
print ("College of Engineering, Information and Industrial Technology")
print ("Bachelor of Science in Information Technology")
print ("2D")
print ("Singing")
print ("Photography")
print ("Baking")
print ("Painting")
print ("Writing")